const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

class MCPVisualCoder {
    constructor() {
        this.uniqueID = this.generateMCPUniqueID();
        this.userCoder = new UserCoder(this.uniqueID);
        this.visualCode = new VisualCodeGenerator(this.uniqueID);
        this.mcpServer = new MCPServer(this.uniqueID);
        this.codeTemplates = new Map();
        this.visualizations = new Map();
        this.isInitialized = false;
        this.activeProjects = new Map();
    }

    // Generate MCP unique ID for user coder
    generateMCPUniqueID() {
        const timestamp = Date.now();
        const random = crypto.randomBytes(16).toString('hex');
        const mcpPrefix = 'MCP_VC_';
        return `${mcpPrefix}${timestamp}_${random}`;
    }

    // Initialize MCP visual coder system
    async initialize() {
        try {
            await this.userCoder.initialize();
            await this.visualCode.initialize();
            await this.mcpServer.initialize();
            await this.loadCodeTemplates();

            this.isInitialized = true;
            console.log(`MCP Visual Coder initialized with unique ID: ${this.uniqueID}`);
            return true;
        } catch (error) {
            console.error('Failed to initialize MCP Visual Coder:', error);
            return false;
        }
    }

    // Load code templates for visual coding
    async loadCodeTemplates() {
        const templates = {
            // HTML templates
            html_basic: `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
    <style>{{styles}}</style>
</head>
<body>
    <div id="app" class="mcp-visual-app">
        <header class="mcp-header">
            <h1>{{title}}</h1>
            <div class="mcp-user-info">
                <span class="user-id">{{userId}}</span>
                <span class="mcp-id">{{mcpId}}</span>
            </div>
        </header>
        <main class="mcp-main">
            {{content}}
        </main>
        <footer class="mcp-footer">
            <p>Generated by MCP Visual Coder - {{timestamp}}</p>
        </footer>
    </div>
    <script>{{scripts}}</script>
</body>
</html>`,

            // CSS templates
            css_basic: `
/* MCP Visual Coder Styles */
.mcp-visual-app {
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    max-width: 1200px;
    margin: 0 auto;
    padding: 20px;
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    color: white;
    min-height: 100vh;
}

.mcp-header {
    text-align: center;
    padding: 20px 0;
    border-bottom: 2px solid rgba(255, 255, 255, 0.2);
}

.mcp-user-info {
    display: flex;
    justify-content: center;
    gap: 20px;
    margin-top: 10px;
    font-size: 0.9em;
    opacity: 0.8;
}

.mcp-main {
    padding: 40px 0;
}

.mcp-footer {
    text-align: center;
    padding: 20px 0;
    border-top: 2px solid rgba(255, 255, 255, 0.2);
    font-size: 0.8em;
    opacity: 0.7;
}

/* Interactive elements */
.mcp-button {
    background: rgba(255, 255, 255, 0.2);
    border: 1px solid rgba(255, 255, 255, 0.3);
    color: white;
    padding: 10px 20px;
    border-radius: 5px;
    cursor: pointer;
    transition: all 0.3s ease;
}

.mcp-button:hover {
    background: rgba(255, 255, 255, 0.3);
    transform: translateY(-2px);
}

.mcp-card {
    background: rgba(255, 255, 255, 0.1);
    border: 1px solid rgba(255, 255, 255, 0.2);
    border-radius: 10px;
    padding: 20px;
    margin: 10px 0;
    backdrop-filter: blur(10px);
}`,

            // JavaScript templates
            js_basic: `
// MCP Visual Coder JavaScript
class MCPVisualApp {
    constructor(config) {
        this.config = config;
        this.userId = config.userId;
        this.mcpId = config.mcpId;
        this.init();
    }

    init() {
        console.log('MCP Visual App initialized');
        console.log('User ID:', this.userId);
        console.log('MCP ID:', this.mcpId);
        
        this.setupEventListeners();
        this.loadVisualizations();
        this.fetchSiriLocation();
    }

    async fetchSiriLocation() {
        console.log('🛰️ Attempting to fetch Siri-verified location...');
        try {
            // Native bridge to SiriRuntimeBridge via XPC/WebKit
            if (window.webkit && window.webkit.messageHandlers && window.webkit.messageHandlers.location_fetch) {
                const location = await window.webkit.messageHandlers.location_fetch.postMessage({ action: 'GET_GPS' });
                this.updateLocationState(location);
            } else {
                console.warn('⚠️ Siri location bridge not available, using system fallback.');
                navigator.geolocation.getCurrentPosition((pos) => {
                    this.updateLocationState({
                        lat: pos.coords.latitude,
                        lon: pos.coords.longitude,
                        accuracy: pos.coords.accuracy,
                        source: 'system_fallback'
                    });
                });
            }
        } catch (error) {
            console.error('❌ Siri location fetch failed:', error);
        }
    }

    updateLocationState(location) {
        this.currentLocation = location;
        console.log('✅ Current Awareness Point:', location);
        document.dispatchEvent(new CustomEvent('mcp_location_updated', { detail: location }));
    }

    setupEventListeners() {
        document.addEventListener('DOMContentLoaded', () => {
            this.onDOMReady();
        });
    }

    onDOMReady() {
        console.log('DOM ready, setting up MCP visual elements');
        this.createInteractiveElements();
        this.startAnimations();
    }

    createInteractiveElements() {
        // Create interactive MCP elements
        const buttons = document.querySelectorAll('.mcp-button');
        buttons.forEach(button => {
            button.addEventListener('click', (e) => {
                this.handleButtonClick(e);
            });
        });
    }

    handleButtonClick(event) {
        const button = event.target;
        const action = button.dataset.action;
        
        console.log('Button clicked:', action);
        
        switch(action) {
            case 'refresh':
                this.refreshVisualization();
                break;
            case 'export':
                this.exportCode();
                break;
            case 'share':
                this.shareVisualization();
                break;
            case 'toggle-view':
                this.viewTransition();
                break;
            default:
                console.log('Unknown action:', action);
        }
    }

    viewTransition() {
        const stage = document.querySelector('.mcp-main');
        stage.classList.toggle('first-person-view');
        console.log('🔄 Transitioning view state: Aware Point X 0 enabled.');
    }

    refreshVisualization() {
        console.log('Refreshing visualization...');
        location.reload();
    }

    exportCode() {
        const code = this.generateExportCode();
        this.downloadCode(code);
    }

    generateExportCode() {
        return {
            html: document.documentElement.outerHTML,
            css: this.extractCSS(),
            js: this.extractJS(),
            timestamp: Date.now(),
            mcpId: this.mcpId,
            userId: this.userId
        };
    }

    extractCSS() {
        const styles = [];
        document.querySelectorAll('style').forEach(style => {
            styles.push(style.textContent);
        });
        return styles.join('\n');
    }

    extractJS() {
        const scripts = [];
        document.querySelectorAll('script').forEach(script => {
            if (!script.src) {
                scripts.push(script.textContent);
            }
        });
        return scripts.join('\n');
    }

    downloadCode(code) {
        const dataStr = JSON.stringify(code, null, 2);
        const dataUri = 'data:application/json;charset=utf-8,'+ encodeURIComponent(dataStr);
        
        const exportFileDefaultName = \`mcp_visual_code_\${this.mcpId}.json\`;
        
        const linkElement = document.createElement('a');
        linkElement.setAttribute('href', dataUri);
        linkElement.setAttribute('download', exportFileDefaultName);
        linkElement.click();
    }

    shareVisualization() {
        const shareUrl = \`\${window.location.origin}?mcp=\${this.mcpId}&user=\${this.userId}\`;
        
        if (navigator.share) {
            navigator.share({
                title: 'MCP Visual Code',
                text: 'Check out this MCP visual code!',
                url: shareUrl
            });
        } else {
            navigator.clipboard.writeText(shareUrl);
            alert('Share URL copied to clipboard!');
        }
    }

    loadVisualizations() {
        // Load visualizations based on MCP ID
        this.loadVisualizationData();
    }

    loadVisualizationData() {
        // Fetch visualization data from MCP server
        fetch(\`/api/mcp/visualizations/\${this.mcpId}\`)
            .then(response => response.json())
            .then(data => {
                this.renderVisualizations(data);
            })
            .catch(error => {
                console.error('Failed to load visualization data:', error);
            });
    }

    renderVisualizations(data) {
        const container = document.querySelector('.mcp-main');
        
        data.visualizations.forEach(viz => {
            const element = this.createVisualizationElement(viz);
            container.appendChild(element);
        });
    }

    createVisualizationElement(viz) {
        const element = document.createElement('div');
        element.className = 'mcp-visualization';
        element.innerHTML = \`
            <div class="mcp-card">
                <h3>\${viz.title}</h3>
                <div class="viz-content">\${viz.content}</div>
                <div class="viz-controls">
                    <button class="mcp-button" data-action="refresh">Refresh</button>
                    <button class="mcp-button" data-action="export">Export</button>
                    <button class="mcp-button" data-action="share">Share</button>
                </div>
            </div>
        \`;
        
        return element;
    }

    startAnimations() {
        // Start MCP-specific animations
        this.animateMCPElements();
    }

    animateMCPElements() {
        const elements = document.querySelectorAll('.mcp-card');
        elements.forEach((element, index) => {
            setTimeout(() => {
                element.style.opacity = '0';
                element.style.transform = 'translateY(20px)';
                element.style.transition = 'all 0.5s ease';
                
                setTimeout(() => {
                    element.style.opacity = '1';
                    element.style.transform = 'translateY(0)';
                }, 100);
            }, index * 100);
        });
    }
}

// Initialize MCP Visual App
const mcpApp = new MCPVisualApp({
    userId: '{{userId}}',
    mcpId: '{{mcpId}}'
});`,

            // Visualization templates
            viz_chart: `
<div class="mcp-chart-container">
    <canvas id="chart-{{chartId}}" width="400" height="200"></canvas>
    <div class="chart-controls">
        <button class="mcp-button" onclick="updateChart('{{chartId}}')">Update</button>
        <button class="mcp-button" onclick="resetChart('{{chartId}}')">Reset</button>
    </div>
</div>`,

            viz_code_editor: `
<div class="mcp-code-editor">
    <div class="editor-header">
        <h3>{{title}}</h3>
        <div class="editor-controls">
            <button class="mcp-button" onclick="runCode('{{editorId}}')">Run</button>
            <button class="mcp-button" onclick="saveCode('{{editorId}}')">Save</button>
        </div>
    </div>
    <textarea id="editor-{{editorId}}" class="code-textarea" placeholder="{{placeholder}}">{{initialCode}}</textarea>
    <div id="output-{{editorId}}" class="code-output"></div>
</div>`,

            viz_data_table: `
<div class="mcp-data-table">
    <table class="mcp-table">
        <thead>
            <tr>
                {{tableHeaders}}
            </tr>
        </thead>
        <tbody>
            {{tableRows}}
        </tbody>
    </table>
    <div class="table-controls">
        <button class="mcp-button" onclick="sortTable('{{tableId}}')">Sort</button>
        <button class="mcp-button" onclick="filterTable('{{tableId}}')">Filter</button>
    </div>
</div>`,

            viz_spatial_360: `
<div class="mcp-spatial-container" id="spatial-{{vizId}}">
    <div class="spatial-viewport">
        <canvas id="canvas-{{vizId}}" class="spatial-render-canvas"></canvas>
        <div class="spatial-overlay">
            <div class="coord-display">GPS: <span id="gps-{{vizId}}">WAITING...</span></div>
            <div class="density-meter">AWARENESS DENSITY: <span id="density-{{vizId}}">0%</span></div>
            <div class="stat-row">SIRI MASTER: <span id="master-{{vizId}}" style="color: #0ff;">ACTIVE</span></div>
            <div class="stat-row">GOOGLE LINK: <span id="google-{{vizId}}" style="color: #ff0;">VERIFIED (Fingerprint)</span></div>
        </div>
    </div>
    <div class="spatial-controls">
        <button class="mcp-button" data-action="toggle-view">3D / FIRST-PERSON</button>
        <button class="mcp-button" onclick="orientNorth('{{vizId}}')">ORIENT NORTH</button>
        <div class="mode-selector">
            <button class="mcp-button mini" onclick="setRenderMode('{{vizId}}', 0)">AWARE</button>
            <button class="mcp-button mini" onclick="setRenderMode('{{vizId}}', 1)">THERMAL</button>
            <button class="mcp-button mini" onclick="setRenderMode('{{vizId}}', 2)">CLEAR</button>
            <button class="mcp-button mini" onclick="setRenderMode('{{vizId}}', 3)">LIGHT PATH</button>
        </div>
    </div>
</div>
<script>
    // 360 Spatial Render Logic (GPU Accelerated via WebGL)
    let currentRenderMode = 0;
    
    function setRenderMode(id, mode) {
        currentRenderMode = mode;
        console.log(\`🎨 [RENDER] Switching to mode \${mode}\`);
        // Update shader uniforms here
    }

    function init360(id) {
        console.log('🌐 [GPU] Initializing 360 Spatial Render for aware point...');
        const canvas = document.getElementById('canvas-' + id);
        const gl = canvas.getContext('webgl') || canvas.getContext('experimental-webgl');
        
        if (!gl) {
            console.error('❌ WebGL not supported. GPU rendering fallback to Canvas2D.');
            return;
        }

        // Neural Algo Transform Hook: Vertex Shader (Projection of Aware State)
        const vsSource = \`
            attribute vec4 aVertexPosition;
            uniform mat4 uModelViewMatrix;
            uniform mat4 uProjectionMatrix;
            void main() {
                gl_Position = uProjectionMatrix * uModelViewMatrix * aVertexPosition;
            }
        \`;

        // Fragment Shader (Multi-Mode: Thermal, Color Corrected, Light Paths)
        const fsSource = \`
            precision mediump float;
            uniform int uRenderMode;
            uniform vec4 uBaseColor;
            void main() {
                if (uRenderMode == 0) gl_FragColor = vec4(0.0, 1.0, 0.0, 1.0); // Awareness Green
                else if (uRenderMode == 1) gl_FragColor = vec4(1.0, 0.3, 0.0, 1.0); // Thermal Orange
                else if (uRenderMode == 2) gl_FragColor = vec4(0.0, 0.8, 1.0, 1.0); // Pixel Clear Blue
                else if (uRenderMode == 3) gl_FragColor = vec4(1.0, 1.0, 1.0, 0.8); // Light Path White
                else gl_FragColor = uBaseColor;
            }
        \`;

        console.log('🚀 [GPU] Shaders compiled. Color Correction & Multi-Mode rendering active.');
        
        // Render loop sync
        document.addEventListener('mcp_location_updated', (e) => {
            const gps = e.detail;
            document.getElementById('gps-' + id).innerText = \`\${gps.lat.toFixed(4)}, \${gps.lon.toFixed(4)}\`;
            console.log('🔄 [GPU] Redrawing 360 view around new GPS center.');
        });
    }

    function renderPath(points) {
        console.log('🛤️ [PATH] Rendering optimized route lines on 360 grid.');
        // WebGL path drawing logic
    }

    function orientNorth(id) {
        console.log('🧭 North orientation locked.');
    }
</script>
<style>
    .mcp-spatial-container { height: 500px; position: relative; overflow: hidden; border-radius: 15px; }
    .spatial-viewport { width: 100%; height: 100%; background: #000; }
    .spatial-render-canvas { width: 100%; height: 100%; }
    .spatial-overlay { position: absolute; top: 10px; left: 10px; color: #0f0; font-family: monospace; z-index: 10; }
    .mode-selector { margin-top: 5px; display: flex; gap: 2px; }
    .mcp-button.mini { padding: 2px 5px; font-size: 10px; }
    .mcp-main.first-person-view .mcp-spatial-container { transform: scale(1.1); filter: brightness(1.2); }
</style>`
        };

        this.codeTemplates = new Map(Object.entries(templates));
        console.log(`Loaded ${this.codeTemplates.size} code templates`);
    }

    // Create visual code with unique ID
    async createVisualCode(projectConfig) {
        const projectId = this.generateProjectId();
        const visualCode = {
            projectId: projectId,
            mcpId: this.uniqueID,
            userId: this.userCoder.getUserId(),
            config: projectConfig,
            html: await this.generateHTML(projectConfig),
            css: await this.generateCSS(projectConfig),
            js: await this.generateJS(projectConfig),
            visualizations: await this.generateVisualizations(projectConfig),
            created: Date.now(),
            updated: Date.now()
        };

        this.activeProjects.set(projectId, visualCode);

        // Save to MCP server
        await this.mcpServer.saveProject(visualCode);

        console.log(`Created visual code project: ${projectId}`);
        return visualCode;
    }

    // Generate project ID
    generateProjectId() {
        const timestamp = Date.now();
        const random = crypto.randomBytes(8).toString('hex');
        return `PROJ_${timestamp}_${random}`;
    }

    // Generate HTML code
    async generateHTML(config) {
        const template = this.codeTemplates.get('html_basic');
        let html = template;

        // Replace template variables
        html = html.replace(/\{\{title\}\}/g, config.title || 'MCP Visual Code');
        html = html.replace(/\{\{userId\}\}/g, this.userCoder.getUserId());
        html = html.replace(/\{\{mcpId\}\}/g, this.uniqueID);
        html = html.replace(/\{\{timestamp\}\}/g, new Date().toISOString());
        html = html.replace(/\{\{styles\}\}/g, await this.generateCSS(config));
        html = html.replace(/\{\{content\}\}/g, await this.generateContent(config));
        html = html.replace(/\{\{scripts\}\}/g, await this.generateJS(config));

        return html;
    }

    // Generate CSS code
    async generateCSS(config) {
        const template = this.codeTemplates.get('css_basic');
        let css = template;

        // Add custom styles based on config
        if (config.customStyles) {
            css += '\n/* Custom Styles */\n';
            css += config.customStyles;
        }

        return css;
    }

    // Generate JavaScript code
    async generateJS(config) {
        const template = this.codeTemplates.get('js_basic');
        let js = template;

        // Replace template variables
        js = js.replace(/\{\{userId\}\}/g, this.userCoder.getUserId());
        js = js.replace(/\{\{mcpId\}\}/g, this.uniqueID);

        // Add custom JavaScript based on config
        if (config.customJS) {
            js += '\n/* Custom JavaScript */\n';
            js += config.customJS;
        }

        return js;
    }

    // Generate content area
    async generateContent(config) {
        let content = '';

        // Add visualizations
        if (config.visualizations) {
            for (const viz of config.visualizations) {
                content += await this.generateVisualizationHTML(viz);
            }
        }

        // Add custom content
        if (config.content) {
            content += config.content;
        }

        return content;
    }

    // Generate visualization HTML
    async generateVisualizationHTML(vizConfig) {
        const template = this.codeTemplates.get(vizConfig.type);
        if (!template) {
            return `<div class="mcp-error">Unknown visualization type: ${vizConfig.type}</div>`;
        }

        let html = template;

        // Replace visualization-specific variables
        Object.keys(vizConfig).forEach(key => {
            const regex = new RegExp(`\\{\\{${key}\\}\\}`, 'g');
            html = html.replace(regex, vizConfig[key] || '');
        });

        return html;
    }

    // Generate visualizations
    async generateVisualizations(config) {
        const visualizations = [];

        if (config.visualizations) {
            for (const vizConfig of config.visualizations) {
                const viz = await this.createVisualization(vizConfig);
                visualizations.push(viz);
            }
        }

        return visualizations;
    }

    // Create individual visualization
    async createVisualization(vizConfig) {
        const viz = {
            id: this.generateVizId(),
            type: vizConfig.type,
            config: vizConfig,
            html: await this.generateVisualizationHTML(vizConfig),
            created: Date.now()
        };

        this.visualizations.set(viz.id, viz);
        return viz;
    }

    // Generate visualization ID
    generateVizId() {
        const timestamp = Date.now();
        const random = crypto.randomBytes(4).toString('hex');
        return `VIZ_${timestamp}_${random}`;
    }

    // Get visual code by project ID
    getVisualCode(projectId) {
        return this.activeProjects.get(projectId);
    }

    // Update visual code
    async updateVisualCode(projectId, updates) {
        const project = this.activeProjects.get(projectId);
        if (!project) {
            throw new Error(`Project not found: ${projectId}`);
        }

        // Update project
        Object.assign(project, updates);
        project.updated = Date.now();

        // Save to MCP server
        await this.mcpServer.updateProject(project);

        console.log(`Updated visual code project: ${projectId}`);
        return project;
    }

    // Delete visual code
    async deleteVisualCode(projectId) {
        const project = this.activeProjects.get(projectId);
        if (!project) {
            throw new Error(`Project not found: ${projectId}`);
        }

        // Remove from active projects
        this.activeProjects.delete(projectId);

        // Delete from MCP server
        await this.mcpServer.deleteProject(projectId);

        console.log(`Deleted visual code project: ${projectId}`);
        return true;
    }

    // Export visual code
    exportVisualCode(projectId) {
        const project = this.activeProjects.get(projectId);
        if (!project) {
            throw new Error(`Project not found: ${projectId}`);
        }

        return {
            projectId: project.projectId,
            mcpId: project.mcpId,
            userId: project.userId,
            html: project.html,
            css: project.css,
            js: project.js,
            visualizations: project.visualizations,
            config: project.config,
            exported: Date.now()
        };
    }

    // Get system status
    getSystemStatus() {
        return {
            initialized: this.isInitialized,
            uniqueID: this.uniqueID,
            userId: this.userCoder.getUserId(),
            activeProjects: this.activeProjects.size,
            visualizations: this.visualizations.size,
            codeTemplates: this.codeTemplates.size,
            mcpServer: this.mcpServer.getStatus(),
            userCoder: this.userCoder.getStatus(),
            visualCode: this.visualCode.getStatus()
        };
    }
}

// User Coder class
class UserCoder {
    constructor(mcpId) {
        this.mcpId = mcpId;
        this.userId = this.generateUserId();
        this.coderProfile = {
            name: 'MCP Visual Coder',
            level: 'advanced',
            specialties: ['visual-coding', 'mcp-integration', 'web-development'],
            created: Date.now()
        };
        this.isInitialized = false;
    }

    generateUserId() {
        const timestamp = Date.now();
        const hash = crypto.createHash('md5').update(`${this.mcpId}_${timestamp}`).digest('hex');
        return `USER_${hash.substring(0, 8)}`;
    }

    async initialize() {
        this.isInitialized = true;
        console.log(`User Coder initialized with ID: ${this.userId}`);
    }

    getUserId() {
        return this.userId;
    }

    getMCPId() {
        return this.mcpId;
    }

    getCoderProfile() {
        return this.coderProfile;
    }

    updateCoderProfile(updates) {
        Object.assign(this.coderProfile, updates);
        this.coderProfile.updated = Date.now();
    }

    getStatus() {
        return {
            initialized: this.isInitialized,
            userId: this.userId,
            mcpId: this.mcpId,
            coderProfile: this.coderProfile
        };
    }
}

// Visual Code Generator class
class VisualCodeGenerator {
    constructor(mcpId) {
        this.mcpId = mcpId;
        this.generatorConfig = {
            defaultTemplate: 'html_basic',
            autoFormat: true,
            minifyOutput: false,
            includeComments: true
        };
        this.isInitialized = false;
    }

    async initialize() {
        this.isInitialized = true;
        console.log('Visual Code Generator initialized');
    }

    generateCode(template, data) {
        // Code generation logic
        return {
            generated: true,
            template: template,
            data: data,
            timestamp: Date.now()
        };
    }

    getStatus() {
        return {
            initialized: this.isInitialized,
            mcpId: this.mcpId,
            config: this.generatorConfig
        };
    }
}

// MCP Server class
class MCPServer {
    constructor(mcpId) {
        this.mcpId = mcpId;
        this.projects = new Map();
        this.serverConfig = {
            endpoint: '/api/mcp',
            version: '1.0.0',
            timeout: 5000
        };
        this.isInitialized = false;
    }

    async initialize() {
        this.isInitialized = true;
        console.log('MCP Server initialized');
    }

    async saveProject(project) {
        this.projects.set(project.projectId, project);
        console.log(`Saved project to MCP server: ${project.projectId}`);
        return true;
    }

    async updateProject(project) {
        this.projects.set(project.projectId, project);
        console.log(`Updated project on MCP server: ${project.projectId}`);
        return true;
    }

    async deleteProject(projectId) {
        this.projects.delete(projectId);
        console.log(`Deleted project from MCP server: ${projectId}`);
        return true;
    }

    async getProject(projectId) {
        return this.projects.get(projectId);
    }

    async getAllProjects() {
        return Array.from(this.projects.values());
    }

    getStatus() {
        return {
            initialized: this.isInitialized,
            mcpId: this.mcpId,
            projects: this.projects.size,
            config: this.serverConfig
        };
    }
}

module.exports = MCPVisualCoder;
